# This is a basic workflow to help you get started with Actions

name: Build Installer

# Controls when the workflow will run
on: 
  push:
    tags:
      - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      
      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: Installer/Fusion-ID-Installer.iss
          options: /O+
      - name: Upload SA
        uses: actions/upload-artifact@v4
        with:
          name: "Installer"
          path: Installer/Output/Fusion-ID-Vanilla-Installer.exe
